/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bsu.fpmi.educational_practice;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.GroupLayout.Group;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.event.CaretEvent;
import javax.swing.event.CaretListener;


/**
 *
 * @author Dmitry Rogozenko,
 * Famcs 2020
 */
public class MyJPanel extends javax.swing.JPanel {
	
        private static final String STR_JRADIOBUTTON1 = "JRadioButton1",
                                    STR_JRADIOBUTTON2 = "JRadioButton2";
        
        private boolean isR1Selected = false, isR2Selected = false;
	
        String buttonStatus = "Button is pressed,";
        String radioB1Status = (isR1Selected ? "selected" : "not selected");
        String radioB2Status = (isR2Selected ? "selected" : "not selected");
        
        String labelText = "", rb1Text, rb2Text, buttonText;
        String labelTag, rb1Tag, rb2Tag, butTag;
        char applyKey;
        
           // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton jButton1;
    private JRadioButton JRadioButton1, JRadioButton2;
    private JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
        
	ActionListener listener = new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent ae) {
                switch ( ((JRadioButton)ae.getSource()).getName()) {
                case STR_JRADIOBUTTON1 :
                        isR1Selected = !isR1Selected;
                        radioB1Status = (isR1Selected ? "selected" : "not selected");
                    break;               
                case STR_JRADIOBUTTON2 :
                        isR2Selected = !isR2Selected;
                        radioB2Status = (isR2Selected ? "selected" : "not selected");
                    break;
                default:
                    break;
                }
            }
    };


    /**
     * Creates new form NewJPanel
     */
    public MyJPanel(String label, String labelTag,
                    String rb1Text, String rb1Tag, 
                    String rb2Text, String rb2Tag,
                    String button, String butTag, 
                    char key) {
        this.labelText = label;
        this.labelTag = labelTag;
        this.rb1Text = rb1Text;
        this.rb1Tag = rb1Tag;
        this.rb2Text = rb2Text;
        this.rb2Tag = rb2Tag;
        this.buttonText = button;
        this.butTag = butTag;
        initComponents();
        setEnterKey(key);
        initEnterKey();
    }

    public void setEnterKey(char key) {
        this.applyKey = key;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        this.jLabel1 = LabelPropertyEditor.getColorLabel(this.labelTag);
        this.jButton1 = ButtonPropertyEditor.getColoredButton(this.butTag);
        this.JRadioButton1 = RadioPropertyEditor.getColoredRadioButton(this.rb1Tag); 
        this.JRadioButton2 = RadioPropertyEditor.getColoredRadioButton(this.rb2Tag); 
        JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        
        this.JRadioButton1.addActionListener(listener);
        this.JRadioButton2.addActionListener(listener);
        this.JRadioButton1.setSelected(this.isR1Selected);
        this.JRadioButton2.setSelected(this.isR2Selected);
        
        //ButtonGroup group = new ButtonGroup();
       // group.add(jRadioButton1);
       // group.add(jRadioButton2);
        
        setToolTipText("");

        this.jLabel1.setText(labelText);
        this.JRadioButton1.setText(rb1Text);
        this.JRadioButton2.setText(rb2Text);        
        this.JRadioButton1.setName(STR_JRADIOBUTTON1);
        this.JRadioButton2.setName(STR_JRADIOBUTTON2);
        this.jButton1.setText(buttonText);
        
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JRadioButton1)
                    .addComponent(jLabel1)
                    .addComponent(JRadioButton2)
                    .addComponent(jButton1))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JRadioButton1)
                .addGap(8, 8, 8)
                .addComponent(JRadioButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(51, Short.MAX_VALUE))
        );

    }// </editor-fold>//GEN-END:initComponents

    private String getFullPanelObjectsStatus(){
        return "Button status: " + this.buttonStatus + "\n" + 
               "RadioButton1 status: " + this.radioB1Status + "\n" + 
               "RadioButton2 status: " + this.radioB2Status;
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(this, this.getFullPanelObjectsStatus());
    }//GEN-LAST:event_jButton1ActionPerformed

    

    private void initEnterKey() {
        jButton1.addKeyListener(new KeyListener() {

            @Override
            public void keyTyped(KeyEvent e) {
                System.out.printf("apply key = '%s'", applyKey);
                System.out.printf(";new char = '%s'\n", e.getKeyChar());
                if (e.getKeyChar() == applyKey) {
                    jButton1.doClick();
                }
            }

            @Override
            public void keyPressed(KeyEvent e) {
            }

            @Override
            public void keyReleased(KeyEvent e) {
            }
        });
    }
}


