/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bsu.fpmi.educational_practice;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

import javax.swing.ButtonGroup;
import javax.swing.GroupLayout.Group;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

public class NewJPanel extends javax.swing.JPanel {

	String STR = "Button is preesed,";
	ActionListener listener = new ActionListener()
    {
        @Override
        public void actionPerformed(ActionEvent ae) {

        }
    };

    private char c;

    /**
     * Creates new form NewJPanel
     */
    public NewJPanel(String staticText, String normalButtonText, String radioButton1, String radioButton2, char confirmButton) {

        initComponents();
//        setEnterKey("a");
        initEnterKey();

        jLabel1.setText(staticText);
        jButton1.setText(normalButtonText);
        jRadioButton1.setText(radioButton1);
        jRadioButton2.setText(radioButton2);
        c=confirmButton;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton(); 
        
        
        jRadioButton1.addActionListener(listener);
        jRadioButton1.setSelected(false);

        jRadioButton2 = new javax.swing.JRadioButton();
        
        jRadioButton2.addActionListener(listener);
        jRadioButton2.setSelected(false);
        
        //ButtonGroup group = new ButtonGroup();
       // group.add(jRadioButton1);
       // group.add(jRadioButton2);
        
        setToolTipText("");

        jLabel1.setText("Static text ");
        
        jRadioButton1.setText("RButton1");
        
        jRadioButton2.setText("RButton2");

        jButton1.setText("Press!");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addComponent(jRadioButton1)
                .addComponent(jRadioButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    )
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        ShowMessge(jButton1.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    
private void ShowMessge(String invokername){
    STR = invokername + " invoked event. \n";
    if(jRadioButton1.isSelected()){
        STR+=jRadioButton1.getText()+" is ON \n";
    }
    else{
        STR+=jRadioButton1.getText()+" is OFF \n";
    }

    if(jRadioButton2.isSelected()){
        STR+=jRadioButton2.getText()+" is ON \n";
    }
    else{
        STR+=jRadioButton2.getText()+" is OFF \n";
    }
    JOptionPane.showMessageDialog(this, STR);
    this.setFocusable(true);
}

    private javax.swing.JButton jButton1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JLabel jLabel1;


    private void initEnterKey() {
        this.setFocusable(true);

        this.addKeyListener(new KeyListener() {

            @Override
            public void keyTyped(KeyEvent e) {
                System.out.println("Clicked! "+e.getKeyChar());
                if (e.getKeyChar() == c) {
                    ShowMessge("Key "+e.getKeyChar());
                }
            }

            @Override
            public void keyPressed(KeyEvent e) {
            }

            @Override
            public void keyReleased(KeyEvent e) {
            }
        });
    }
}


